<?xml version="1.0" encoding="utf-8"?>
<Database Name="Apollo.AIM.SNAP" Class="SNAPDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DWAXCAPB006;Initial Catalog=Apollo.AIM.SNAP;Integrated Security=True" SettingsObjectName="Apollo.AIM.SNAP.Properties.Settings" SettingsPropertyName="Apollo_AIM_SNAPConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SNAP_Access_Details_Form" Member="SNAP_Access_Details_Forms">
    <Type Name="SNAP_Access_Details_Form">
      <Column Name="pkId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="parentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="label" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="isActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isRequired" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="SNAP_Access_Details_Form_SNAP_Access_User_Text" Member="SNAP_Access_User_Texts" ThisKey="pkId" OtherKey="access_details_formId" Type="SNAP_Access_User_Text" />
    </Type>
  </Table>
  <Table Name="dbo.SNAP_Workflow_State_Type" Member="SNAP_Workflow_State_Types">
    <Type Name="SNAP_Workflow_State_Type">
      <Column Name="pkId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="typeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SNAP_Access_User_Text" Member="SNAP_Access_User_Texts">
    <Type Name="SNAP_Access_User_Text">
      <Column Name="pkId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="requestId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="access_details_formId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="userText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="modifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="SNAP_Access_Details_Form_SNAP_Access_User_Text" Member="SNAP_Access_Details_Form" ThisKey="access_details_formId" OtherKey="pkId" Type="SNAP_Access_Details_Form" IsForeignKey="true" />
      <Association Name="SNAP_Request_SNAP_Access_User_Text" Member="SNAP_Request" ThisKey="requestId" OtherKey="pkId" Type="SNAP_Request" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SNAP_Actor_Group" Member="SNAP_Actor_Groups">
    <Type Name="SNAP_Actor_Group">
      <Column Name="pkId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="groupName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="actorGroupType" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="isActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="SNAP_Actor_Group_SNAP_Actor" Member="SNAP_Actors" ThisKey="pkId" OtherKey="actor_groupId" Type="SNAP_Actor" />
    </Type>
  </Table>
  <Table Name="dbo.SNAP_Actor_Group_Type" Member="SNAP_Actor_Group_Types">
    <Type Name="SNAP_Actor_Group_Type">
      <Column Name="pkId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="typeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SNAP_Actors" Member="SNAP_Actors">
    <Type Name="SNAP_Actor">
      <Column Name="pkId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="actor_groupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="userId" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="displayName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="emailAddress" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="isDefault" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="isActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="SNAP_Actor_SNAP_Workflow" Member="SNAP_Workflows" ThisKey="pkId" OtherKey="actorId" Type="SNAP_Workflow" />
      <Association Name="SNAP_Actor_Group_SNAP_Actor" Member="SNAP_Actor_Group" ThisKey="actor_groupId" OtherKey="pkId" Type="SNAP_Actor_Group" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SNAP_Comments_Type" Member="SNAP_Comments_Types">
    <Type Name="SNAP_Comments_Type">
      <Column Name="pkId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="typeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="audience" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SNAP_Request_Comments" Member="SNAP_Request_Comments">
    <Type Name="SNAP_Request_Comment">
      <Column Name="pkId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="requestId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="commentTypeEnum" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="commentText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="createdDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="SNAP_Request_SNAP_Request_Comment" Member="SNAP_Request" ThisKey="requestId" OtherKey="pkId" Type="SNAP_Request" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SNAP_Request_State_Type" Member="SNAP_Request_State_Types">
    <Type Name="SNAP_Request_State_Type">
      <Column Name="pkId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="typeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SNAP_Requests" Member="SNAP_Requests">
    <Type Name="SNAP_Request">
      <Column Name="pkId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="submittedBy" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="userId" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="userDisplayName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="userTitle" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="managerUserId" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="managerDisplayName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ticketNumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="isChanged" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="statusEnum" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="createdDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="lastModifiedDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="SNAP_Request_SNAP_Access_User_Text" Member="SNAP_Access_User_Texts" ThisKey="pkId" OtherKey="requestId" Type="SNAP_Access_User_Text" />
      <Association Name="SNAP_Request_SNAP_Request_Comment" Member="SNAP_Request_Comments" ThisKey="pkId" OtherKey="requestId" Type="SNAP_Request_Comment" />
      <Association Name="SNAP_Request_SNAP_Workflow" Member="SNAP_Workflows" ThisKey="pkId" OtherKey="requestId" Type="SNAP_Workflow" />
    </Type>
  </Table>
  <Table Name="dbo.SNAP_Weekends_and_Holidays" Member="SNAP_Weekends_and_Holidays">
    <Type Name="SNAP_Weekends_and_Holiday">
      <Column Name="dayOfWeekDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="dayName" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SNAP_Workflow" Member="SNAP_Workflows">
    <Type Name="SNAP_Workflow">
      <Column Name="pkId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="requestId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="actorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SNAP_Workflow_SNAP_Workflow_Comment" Member="SNAP_Workflow_Comments" ThisKey="pkId" OtherKey="workflowId" Type="SNAP_Workflow_Comment" />
      <Association Name="SNAP_Workflow_SNAP_Workflow_State" Member="SNAP_Workflow_States" ThisKey="pkId" OtherKey="workflowId" Type="SNAP_Workflow_State" />
      <Association Name="SNAP_Actor_SNAP_Workflow" Member="SNAP_Actor" ThisKey="actorId" OtherKey="pkId" Type="SNAP_Actor" IsForeignKey="true" />
      <Association Name="SNAP_Request_SNAP_Workflow" Member="SNAP_Request" ThisKey="requestId" OtherKey="pkId" Type="SNAP_Request" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SNAP_Workflow_Comments" Member="SNAP_Workflow_Comments">
    <Type Name="SNAP_Workflow_Comment">
      <Column Name="pkId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="workflowId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="commentTypeEnum" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="commentText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="createdDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="SNAP_Workflow_SNAP_Workflow_Comment" Member="SNAP_Workflow" ThisKey="workflowId" OtherKey="pkId" Type="SNAP_Workflow" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SNAP_Workflow_State" Member="SNAP_Workflow_States">
    <Type Name="SNAP_Workflow_State">
      <Column Name="pkId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="workflowId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="workflowStatusEnum" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="notifyDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="dueDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="completedDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Association Name="SNAP_Workflow_SNAP_Workflow_State" Member="SNAP_Workflow" ThisKey="workflowId" OtherKey="pkId" Type="SNAP_Workflow" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.usp_insert_request_xml" Method="usp_insert_request_xml">
    <Parameter Name="request_data" Type="System.Xml.Linq.XElement" DbType="Xml" />
    <Parameter Name="submittedBy" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="userId" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="userDisplayName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="userTitle" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="managerUserId" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="managerDisplayName" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_open_my_request_comments" Method="usp_open_my_request_comments">
    <Parameter Name="userId" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="usp_open_my_request_commentsResult">
      <Column Name="pkId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="requestId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="commentTypeEnum" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="commentText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="createdDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_open_my_request_details" Method="usp_open_my_request_details">
    <Parameter Name="userId" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="usp_open_my_request_detailsResult">
      <Column Name="pkId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="submittedBy" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="userId" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="userDisplayName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="userTitle" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="managerUserId" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="managerDisplayName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ticketNumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="isChanged" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="statusEnum" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="createdDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="lastModifiedDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_open_my_request_text" Method="usp_open_my_request_text">
    <Parameter Name="userId" Type="System.String" DbType="NVarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_open_my_request_workflow_comments" Method="usp_open_my_request_workflow_comments">
    <Parameter Name="userId" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="usp_open_my_request_workflow_commentsResult">
      <Column Name="requestId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pkId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="workflowId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="commentTypeEnum" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="commentText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="createdDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_open_my_request_workflow_details" Method="usp_open_my_request_workflow_details">
    <Parameter Name="userId" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="usp_open_my_request_workflow_detailsResult">
      <Column Name="requestId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pkId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="workflowId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="workflowStatusEnum" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="notifyDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="dueDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="completedDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="pkId1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="actor_groupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="userId" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="displayName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="emailAddress" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="isDefault" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="isActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_open_request_details" Method="usp_open_request_details">
    <Parameter Name="userId" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="requestId" Type="System.Int32" DbType="Int" />
    <ElementType Name="usp_open_request_detailsResult">
      <Column Name="requestId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="submittedBy" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="userId" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="userDisplayName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="userTitle" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="managerUserId" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="managerDisplayName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="fieldId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fieldLabel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="fieldText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="modifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ticketNumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="isChanged" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="statusEnum" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="createdDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_open_request_tab" Method="usp_open_request_tab">
    <Parameter Name="userId" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="requestId" Type="System.Int32" DbType="Int" />
    <ElementType Name="usp_open_request_tabResult">
      <Column Name="requestId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="submittedBy" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="userId" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="userDisplayName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="userTitle" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="managerUserId" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="managerDisplayName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="fieldId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fieldLabel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="fieldText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="modifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ticketNumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="isChanged" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="statusEnum" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="createdDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_requests" Method="usp_requests">
    <Parameter Name="userId" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="role" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="usp_requestsResult">
      <Column Name="pkId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="submittedBy" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="userId" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="userDisplayName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="userTitle" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="managerUserId" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="managerDisplayName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ticketNumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="isChanged" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="statusEnum" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="createdDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="lastModifiedDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>