using System;
using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("2.2.0")]
[assembly: AssemblyCopyrightAttribute("Copyright 2010-2011 Apollo Group Inc.")]
[assembly: AssemblyCompanyAttribute("Apollo Group Inc.")]
[assembly: AssemblyProductAttribute("Supplemental/Computer Access Process")]

